select * from customer_behaviour limit 30;
--Q1. What is the total revenue generated by male vs. female customers? 

select gender,sum(purchase_amount) as total_revenue
from customer_behaviour
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id 
from customer_behaviour
where discount_applied='Yes' and
purchase_amount >(select avg(purchase_amount) from customer_behaviour)

--Q3. Which are the top 5 products with the highest average review rating? 
select item_purchased,ROUND(avg(review_rating)::numeric,2) as avg_review
from customer_behaviour
group by item_purchased
order by avg_review desc limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,avg(purchase_amount) as avg_amount,
from customer_behaviour
where shipping_type in ( 'Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 

select subscription_status,
count(customer_id) as Total_custmr,
sum(purchase_amount) as total_amount,
round(avg(purchase_amount),2) as avg_amount
from customer_behaviour
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied? 

select item_purchased,
count(item_purchased) as total_quantity,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_qunty
from customer_behaviour
group by item_purchased
order by discount_qunty desc limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with cte as(
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer_behaviour
)
select customer_segment,
count(*) as total_customer
from cte
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with cte as(select category,item_purchased,count(customer_id) as total_item,
row_number() over( partition by category order by count(item_purchased) desc) as rnk
from customer_behaviour
group by category,item_purchased
)
select category,item_purchased,total_item
from cte
where rnk<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
select subscription_status, count(customer_id) as total_customer
from customer_behaviour
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_amount,
round(sum(purchase_amount)*100/(select sum(purchase_amount) from customer_behaviour),2) as perent_contribute
from customer_behaviour
group by age_group
